package com.movie.reservation.movie;

public enum Genre {
    ACTION, ADVENTURE, COMEDY, CRIME, DRAMA, FANTASY, HISTORICAL, HORROR, MYSTERY, ROMANCE,
    SCIENCE_FICTION, THRILLER, WESTERN, ANIMATION, DOCUMENTARY, MUSICAL, WAR, BIOGRAPHY,
    SPORTS, FAMILY, NOIR, SUPERHERO
}
